### PR TITLE
[WIP]Add support for multiple approval workflows

### PR DESCRIPTION
**Pull request by lgalis**
First draft for this - layout will change.
Screenshot from 2020-01-24 15-51-18

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@lgalis there seems to be an issue with the add workflow button if no workflow was selected:
workflow-crash

**Comment by lgalis** [comment]
@Hyperkid123 - thanks, I'll disable the add button when there's no selection.

**Comment by Hyperkid123** [comment]
@lgalis also I found that it is possible to add same workflow multiple times
workflow-crash

**Comment by Hyperkid123** [comment]
Also, I think using multi-select would be enough.

Do we have some mocks for this?

screenshot-ci foo redhat com_1337-2020 01 28-16_22_30

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 there are no mocks for the redesign of this. it's on my backlog. but you are correct by using the multi-select component. 

I'm curious as to what the "Add workflow" primary button does. We should only have one primary button on this modal.

Approval workflow also has been renamed "Approval process" to avoid the confusion with Ansible's job/workflow template terms.

**Comment by lgalis** [comment]
@Hyperkid123 - I have considered the multiselect, but decided to model this based on the role selection in the rbac ui - I had a mock for that. I do not look of the multiselect. The workflows do have a description - which I would like to add to the table ( it is not returned for the assigned workflow now, but I can look it up).

**Comment by lgalis** [comment]
@sbuenafe - @Hyperkid123 screenshot is not what is in this PR - the screenshot in the description is.
If you want to go with the multiselect, then I will change to that.

**Comment by lgalis** [comment]
@sbuenafe-rh - @Hyperkid123's screenshot is not what is in this PR - the screenshot in the description is.
If you want to go with the multiselect, then I will change to that - there will be no 'Add workflow' button if we do that.
Also the 'Approval process' change - was that the final decision?

**Comment by sbuenafe-rh** [comment]
@lgalis "Approval process" term was vetted with John and with UXD content strategist. If the term changes again, then we can revisit it. Using process instead of workflow, we can bypass the confusion with Ansible's use of "workflow".

**Comment by gmcculloug** [comment]
@sbuenafe-rh The term "Approval process" term impacts the Approval UI as well since we use the term "Workflow" in several places there.  I can open an issue for this, but do we have mocks or the term to use there?  If you are already in the Approval UI would you refer to them as "Processes"?

**Comment by lgalis** [comment]
Closing this PR - Replaced by https://github.com/RedHatInsights/catalog-ui/pull/390

**Pull request closed without merging**
