### PR TITLE
Add advanced filtering to portfolios screen

### PR DESCRIPTION
**Pull request by Hyperkid123**
jira: https://projects.engineering.redhat.com/browse/SSP-1725, https://projects.engineering.redhat.com/browse/SSP-1692

### Changes
- use primary toolbar for portfolios
- add multi-filtering support
  - user can filter by name or owner
- add sorting support
  - only by one attribute since that is what current API supports
  - sortable parameters are name, owner, created_at, updated_at

- [x] translate strings

advanced-filter-portfolios

### CODE REVIEW

**Comment by Hyperkid123** [comment]
> Works great!
> 
> I just found this visual bug, but it happens also on Sources, so it's probably something in FC/PF.
> 
> image

And to which bug are you referring sir? (I can't see :hankey: )

**Comment by rvsia** [comment]
@Hyperkid123 There should be space between groups.

https://www.patternfly.org/v4/img/8814ad7dd4e8a377d59db962785b86bb-faceted-combo-chips.png

**Comment by Hyperkid123** [comment]
Ah, that. Well, there is only one group. That is how the primary toolbar was implemented.

**Comment by Hyperkid123** [comment]
@lgalis of course! I have totally forgot about that. Give me a minute.

**Comment by Hyperkid123** [comment]
@lgalis empty states were fixed. The empty state middleware was not ready for multi-attribute filtering

screenshot-ci foo redhat com_1337-2020 07 29-16_36_45

**Pull request merged**
