### PR TITLE
Migrate platform presentational components and order notification to TS.

### PR DESCRIPTION
**Pull request by Hyperkid123**

### CODE REVIEW

**Review by rvsia — APPROVED** [review]

**Comment by rvsia** [comment]
@Hyperkid123  there are some typing errors

**Comment by Hyperkid123** [comment]
@rvsia ah I forgot to add types to the placeholders file. It should be OK now.

**Comment by Hyperkid123** [comment]
We have some snapshots mismatch. Taking a look.

**Comment by Hyperkid123** [comment]
Ah these snapshot failures are caused by the change of the default props definition. If the `defaultProps` is used, then the prop is injected to the component from "above" and is seen in the virtual dom. If we assign the props when destructing the props the prop value only exists inside the function, therefore they are not visible in the virtual DOM.

**Review by lgalis — APPROVED** [review]

**Pull request merged**
