### PR TITLE
[prod-beta] Merge main to prod-beta

### PR DESCRIPTION
**Pull request by lgalis**
To be merged after the config pr: https://github.com/RedHatInsights/cloud-services-config/pull/837

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@lgalis what is the timeline for this. The CSC PR will take around 15-25 minutes to be deployed. I would advise merging this after the config PR is deployed.

**Comment by lgalis** [comment]
@Hyperkid123 - no rush - can be merged after the config PR

**Comment by Hyperkid123** [comment]
@lgalis so we want the CSC config in all envs up to prod beta? Including ci/qa/stage stable?

**Comment by Hyperkid123** [comment]
@lgalis please do not merge this yet. The CSC has been merged but Jenkins is having a hard time actually deploy it. I will let you know once its OK.

**Review by eclarizio — APPROVED** [review]

**Comment by eclarizio** [comment]
@Hyperkid123 Laura is out on PTO this week, please ping me when this is ready 👍

**Comment by Hyperkid123** [comment]
@eclarizio you can merge the PR now.

**Pull request merged**
