### PR TITLE
Enable reset portfolio item icon.

### PR DESCRIPTION
**Pull request by Hyperkid123**
jira: https://issues.redhat.com/browse/SSP-1755

~~blocked by: https://github.com/RedHatInsights/catalog-api/pull/793~~

after clicking on the icon dropdown will appear with change/reset options:

reset-icon

cc @sbuenafe-rh I have stolen common patterns for multi icon operations actions. Feel free to change it later.

### CODE REVIEW

**Comment by gmcculloug** [comment]
@Hyperkid123 With the dependent PR RedHatInsights/catalog-api#793 merged can this PR move forward?

**Comment by Hyperkid123** [comment]
@gmcculloug there is actually one more: https://github.com/RedHatInsights/catalog-api/pull/806. We needed to permit the parameter in the controller as well not just in OpenApi spec.

**Comment by eclarizio** [comment]
https://github.com/RedHatInsights/catalog-api/pull/806 has been merged. Looks like travis is failing here so once that's fixed we can probably get this in.

**Comment by sbuenafe-rh** [comment]
@Hyperkid123 can the dropdown be placed closer and underneath the pencil icon? 

And can we change the dropdown menu items to:
1) **Upload image**
2) **Reset image**

**Comment by Hyperkid123** [comment]
@sbuenafe-rh it can be closer and we can change the text.

**Review by lgalis — APPROVED** [review]
Looks good.

**Pull request merged**
